[build-system]
requires = ["pdm-pep517>=0.8.5"]
build-backend = "pdm.pep517.api"

[project]
name = "cognosis"
description = "A namespace and filesystem interface for Obsidian knowledge bases."
authors = [{ name = "MOONLAPSED", email = "MOONLAPSED@gmail.com" }]
requires-python = ">=3.13"
version = "0.4.20"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.pdm.dev-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "pytest-benchmark",
]
lint = [
    "flake8",
    "black",
    "isort",
    "mypy",
]
dev = [
    "nox",
    "pre-commit",
    "cffi",
    "cmake",
    "uv",
]

[tool.pdm.conda.pypi-mapping]
download-dir = "/tmp"
url = "https://url/to/mapping.yaml"

[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.13"
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.scripts]
main = "main:main"
lint = "flake8 ."
format = { composite = ["black .", "isort ."] }
typecheck = "mypy ."
test = "pytest"

[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/seeds"]
