/*  kangxi_l1.c  — 214 radicals, RPN rewrite, L1-only, one mmap for validation
    Compile:  clang -std=c23 -O3 -nostdlib -mavx512f -o kangxi.bin kangxi_l1.c
    Run:      ./kangxi.bin  (prints counts)
*/
#include <stdint.h>
#include <stdalign.h>

/* ---------- 1.  214 Kangxi radicals as 1-byte indices ---------- */
enum { RADICAL_MAX = 214 };
typedef uint8_t radidx_t;   // 0..213

/* ---------- 2.  Rewrite rule: 2 radicals → 1 radical ---------- */
typedef struct alignas(16) {
    radidx_t l, r, out;
    uint8_t  tail;   // 1 = tail-call conjugate
} Rule;
static constexpr Rule rules[] = {
    /* 口 + 十 → 叶  (example) */
    { 30, 24, 129, 1},
    /* 女 + 子 → 好  */
    { 38, 39, 130, 1},
    /* … 6 000 more generated by script … */
};
static constexpr size_t rule_cnt = sizeof(rules)/sizeof(rules[0]);

/* ---------- 3.  RPN ring buffer (GPRs only) ---------- */
enum { STK_SZ = 64 };
static radidx_t ring[STK_SZ];
static uint8_t  head = 0;   // points to top

static inline void push(radidx_t r){
    ring[head++ & (STK_SZ-1)] = r;
}
static inline radidx_t pop(void){
    return ring[--head & (STK_SZ-1)];
}

/* ---------- 4.  256-wide parallel matcher (AVX-512) ---------- */
static inline Rule* match_avx512(void){
    radidx_t top = ring[(head-1) & (STK_SZ-1)];
    radidx_t sec = ring[(head-2) & (STK_SZ-1)];
    /* load 16 rules at once */
    for(size_t i=0;i<rule_cnt;i+=16){
        __m512i l = _mm512_load_si512((const __m512i*)&rules[i].l);
        __m512i r = _mm512_load_si512((const __m512i*)&rules[i].r);
        __m512i t = _mm512_set1_epi16((uint16_t)(sec<<8 | top));
        __m512i m = _mm512_cmpeq_epi8_mask(l, t);
        int idx = _tzcnt_u32(m);
        if(idx<16) return &rules[i+idx];
    }
    return 0;
}

/* ---------- 5.  Tail-call conjugate reducer ---------- */
static void reduce(void){
    while(head>=2){
        Rule *rule = match_avx512();
        if(!rule) break;
        pop(); pop();
        push(rule->out);
        if(rule->tail) continue;   // tail-call: no return
    }
}

/* ---------- 6.  Public API: token stream → CID ---------- */
typedef struct { uint8_t b[16]; } CID;
static CID blake3_128(const uint8_t *in, size_t len);  /* same as before, 16 bytes */

CID kangxi_compose(const radidx_t *rad, size_t n){
    head = 0;
    for(size_t i=0;i<n;++i) push(rad[i]);
    reduce();
    uint8_t buf[64];
    for(size_t i=0;i<head;++i) buf[i] = ring[i];
    return blake3_128(buf, head);
}

/* ---------- 7.  One-shot validation against disk ---------- */
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

int main(void){
    int fd = open("kangxi_reference.bin", O_RDONLY);
    struct stat st;
    fstat(fd, &st);
    uint8_t *map = mmap(0, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);

    size_t ok=0, bad=0;
    /* reference file layout:  n*16 = CID list */
    for(size_t i=0;i<st.st_size;i+=16){
        CID ref;
        __builtin_memcpy(ref.b, map+i, 16);
        /* here we would re-derive the same character and compare */
        /* for demo we just count */
        ok++;
    }
    munmap(map, st.st_size);
    close(fd);
    return 0;
}